name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_C0CZLC3YFPTQ7hHPqTlOnvEEYhQu/QrxKoBumRQ
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_euKAhc1E8Pza1Dm9RlHkRsvxKW4K/8xqf4FVNTR
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_kOgv0BbZ470H5o9qA26QpFGCUtXJ/MtNAcoWI6h



