name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_c2P7ulpHJC6inhzSImoy5w57XZt6/FAv5qv6IBv
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_gZYs9lCxIa97WWPhgMO0y6FpnpIH/FgsWFHKFtM
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QLZx9oTfhlTJwSYQQQejOKY1dEdL/XI8Yy5pM0G

        
